name = "Acme Light"
license = "MIT"
licenselink = ""
description = "A minimal Hugo theme inspired by Plan9 Acme, light theme"
homepage = ""
tags = ["minimal", "light", "acme"]
features = ["syntax highlighting", "mermaid diagrams"]
min_version = "0.41.0"

[author]
  name = "opencode"
  homepage = ""